accent = "#a0a0a0"
cursor = "#d0d0d0"
foreground = "#d0d0d0"
background = "#1a1a1a"
selection_foreground = "#ffffff"
selection_background = "#333333"

color0 = "#2a2a2a"
color1 = "#808080"
color2 = "#909090"
color3 = "#a0a0a0"
color4 = "#b0b0b0"
color5 = "#c0c0c0"
color6 = "#d0d0d0"
color7 = "#e0e0e0"
color8 = "#3a3a3a"
color9 = "#808080"
color10 = "#909090"
color11 = "#a0a0a0"
color12 = "#b0b0b0"
color13 = "#c0c0c0"
color14 = "#d0d0d0"
color15 = "#f0f0f0"
