# ────────────────────────────────────────────────────────────
# Omarchy Theme for Hyprland
# ────────────────────────────────────────────────────────────

general {
    col.active_border = rgb(000000)
    col.inactive_border = rgb(1a1a1a)
    border_size = 0
    gaps_in = 6
    gaps_out = 20
}

animations {
    enabled = yes
    bezier = calm, 0.25, 0.9, 0.35, 1
    animation = windows,     1, 4, calm
    animation = windowsIn,   1, 4, calm
    animation = windowsOut,  1, 3, calm
    animation = windowsMove, 1, 4, calm
    animation = fade,        1, 3, calm
    animation = fadeIn,      1, 3, calm
    animation = fadeOut,     1, 2, calm
    animation = layers,      1, 3, calm
    animation = layersIn,    1, 3, calm
    animation = layersOut,   1, 2, calm
    animation = workspaces,  1, 4, calm
}

decoration {
    rounding = 20
    shadow {
        enabled = true
        range = 15
        render_power = 5
        offset = 0 0
    }
    blur {
        enabled = true
        size = 2
        passes = 4
        contrast = 1.1
        brightness = 1.1
        vibrancy = 0.2
        vibrancy_darkness = 0.2
        noise = 0.03
        ignore_opacity = true
        new_optimizations = on
    }
    active_opacity = 0.92
    inactive_opacity = 0.88
    fullscreen_opacity = 1.0
}

layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0, match:namespace walker
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace notifications
layerrule = blur on, match:namespace vicinae
layerrule = blur on, match:namespace swayosd
layerrule = ignore_alpha 0.1, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace vicinae
