[meta]
version = 1
name = "BlackBlur2"
description = "Follow your BlackBlur2 system theme."
variant = "dark"
inherits = "vicinae-dark"
icon = "/home/atif/.local/share/omarchy/icon.png"

[colors.core]
background = "#1a1a1a"
foreground = "#d0d0d0"
secondary_background = "#2a2a2a"
border = "#333333"
accent = "#a0a0a0"

[colors.list.item.hover]
background = "#333333"
foreground = "#d0d0d0"

[colors.list.item.selection]
background = "#3a3a3a"
foreground = "#d0d0d0"

[colors.accents]
blue = "#b0b0b0"
green = "#909090"
magenta = "#c0c0c0"
orange = "#a0a0a0"
purple = "#c0c0c0"
red = "#808080"
yellow = "#a0a0a0"
cyan = "#d0d0d0"
